### ISSUE TITLE
Overlapping Text in Thead

### ISSUE THREAD

**Issue by loicdev** [KnpLabs/snappy#201]
Hello i have a probleme when a generate a PDF with big table row.
Example of top of secondary page

![pasted image at 2016_01_13 06_48 pm](https://cloud.githubusercontent.com/assets/6772726/12324860/224e956e-bac6-11e5-9f8c-1f0d9a100db6.png)

I have tried to use this CSS tips that i have found in many discussion : 
tr {page-break-inside: avoid; }

But it does not work when my row is longer than a page..
Please , any help ?

**Comment by NiR-** [comment]
This issue is recurrent with wkhtmltopdf. Accordingly to [this issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3159), and [this other one](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3356), you should use following css rules:

```css
table { page-break-inside:auto }
tr    { page-break-inside:avoid; page-break-after:auto }
thead { display:table-header-group }
tfoot { display:table-footer-group }
```

I'm closing this issue because it has already been answered here and on wkhtmltopdf's repo.
