### ISSUE TITLE
Problem with japanese characters

### ISSUE THREAD

**Issue by eved42** [KnpLabs/snappy#424]
Hello,

I use your bundle (v 1.5) on a Symfony 3.4 project. I manage the generation of a PDF into multiple languages. The user selects a language and the PDF is generated with the corresponding translations.

I have no problem with accented characters (French, Spanish...) or with cyrillic characters (Russian, Ukrainian...) but my Japanese translations (kanjis) are not displayed at all whereas they are displayed correctly in the browser (in the same font).

- If I used "TT Norms" font : no characters are displayed.
- If I use "Open Sans" font : I have bordered squares instead of kanjis.

I have no problem in the browser with these two fonts, characters are displayed properly.

config.yml
```
knp_snappy:
    pdf:
        enabled: true
        binary: '/bin/wkhtmltopdf'
        options:
           encoding: utf-8
           print-media-type: true
           page-size: A4
           dpi: 300
           image-quality: 80
           margin-left:   15mm
           margin-right:  15mm
           margin-top:    50mm
           margin-bottom: 25mm
```
Controller : 
```
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;

$html = $this->renderView('public/products/pdf/content.html.twig', array(
    'lang'  => $lang
));

return new PdfResponse(
    $this->get('knp_snappy.pdf')->getOutputFromHtml($html),
    'product.pdf'
);
```

I added `<meta charset="UTF-8">` and `<meta http-equiv="Content-type" content="text/html; charset=utf-8" />` inside the `<head>` of my Twig view.

If I do a `locale -a` on my server, here is the result : 
```
C
C.UTF-8
fr_FR.utf8
POSIX
```

Examples of text I want to display : 
- 参照
- 製品ライン
- アイテム
- コード化

Do you have an idea of the problem ? I don't if it's a problem of encoding or if it comes from the font or another thing.
