### ISSUE TITLE
Error setting option

### ISSUE THREAD

**Issue by jdewit** [KnpLabs/snappy#51]
``` yaml
knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf-amd64
        options:    
          redirect-delay: 1000
```

throws an invalid option exception

Removing lines 70-72 from Knp\Snappy\AbstractGenerator.php solves the problem but I see that this provides some validation.

How do I set the allowed options using the snappy-bundle?
